name: Publish to AWS CodeArtifact

on:
  push:
    tags:
      - "v*"             # publish on tags like v1.2.3

permissions:
  id-token: write        # required for OIDC
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CA_DOMAIN: ${{ vars.CA_DOMAIN }}
  CA_DOMAIN_OWNER: ${{ vars.CA_DOMAIN_OWNER }} 
  CA_REPO: ${{ vars.CA_REPO }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.CA_DOMAIN_OWNER }}:role/immutable-bakkery-iac-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build the package (wheel/sdist)
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Get CodeArtifact token & Twine config
        run: |
          python -m pip install twine
          aws codeartifact login \
            --tool twine \
            --domain "$CA_DOMAIN" \
            --domain-owner "$CA_DOMAIN_OWNER" \
            --repository "$CA_REPO"

      - name: Publish to CodeArtifact
        run: |
          python -m twine upload --repository codeartifact dist/*
