name: Build Python wheel

on:
  push:
    branches: [ main, master ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build backend
        run: |
          python -m pip install -U pip build

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Upload wheel as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist

      - name: Create GitHub Release and upload wheel
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
