name: Publish Release Artifact

on:
  workflow_call:

permissions:
  contents: write
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist

      - name: Create GitHub Release and upload wheel
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
